ast.go, parser.go
=> Fix build errors, implement parseCommaList

ast.go, lexer.go, lexer_test.go, parser.go, static_error.go
With this commit, I grant a Copyright License in this project submitted up until now to Google under the terms of the Google CLA.  See https://cla.developers.google.com/about/google-individual.
=> Add copyright notice to all files.

README.md
@sparkprime You'll probably have to set up travis and the coverage tool as I'm not an admin on the repo.  We also need to enable issues on this repo so that users can submit golang specific issues.
=> Fix up repo paths in the README.

ast.go, lexer_test.go, parser.go, parser_test.go
Our code coverage is at ~83%.  It would be higher except that the generated code doesn't have tests.
=> Finish writing unit tests for parser

lexer.go, parser_test.go
When the lexer backed up, no matter from what character it went
to the previous line.
=> Fix bug messing up newlines

testdata/bad_function_call.golden, testdata/bad_function_call.jsonnet, testdata/bad_function_call2.golden, testdata/bad_function_call2.jsonnet, testdata/bad_function_call_and_error.golden, testdata/bad_function_call_and_error.jsonnet, thunks.go, value.go
To be expanded when optional arguments arrive.
=> Simplistic argument checking

imports.go, main_test.go, vm.go
It was already there, it was a matter of exposing it in the API
=> Support for import callbacks

builtins.go, interpreter.go, value.go
A field on it's own is not a value
=> Rename valueSimpleObjectField -> simpleObjectField

interpreter.go
=> Rename 'ast' variable that shadowed package name.

main_test.go, thunks.go, vm.go
=> Make NativeFunction members public

vm.go
=> Add Version()

builtins.go, evaluator.go, testdata/bitwise_and3.golden
=> Allow bitwise operations on floats, according to Spec (and Javascript behavior)

interpreter.go, jsonnet/cmd.go, jsonnet/cmd_test.go, main_test.go, vm.go
=> Feature-complete commandline interface

README.md, dump/dump.go, dump/utils.go, reset_stdast_go.sh, std.go
@mqliang I'm going to commit this because it fixes the build but please take a look anyway.
=> Fix unparsing of enums, avoid static type error

imports.go
@sbarzowski @hausdorff @eicnix
=> Make fields of ImportedData public

jsonnet/cmd.go
Finish off https://github.com/google/jsonnet/issues/411
=> Add JSONNET_PATH (go version)

thunks.go
Instead of crashing with internal error
=> Make errors in native functions runtime errors

main_test.go
A step towards a unified test suite. In particular this
lets us use C++ version with Go tests. The problem remains
that errors (both static and runtime) may differ between implementations.
This will require special handling. C++ version seems to pass all
"positive" tests. Go version also has this problem (error formatter used in tests is different).
Also native functions etc. are not handled in any way at the moment.
=> Basic support for running jsonnet command in tests

builtins.go
@sbarzowski tests.sh was failing since you wrote this optimized version
failing test: https://github.com/google/jsonnet/blob/master/test_suite/stdlib.jsonnet#L181
=> std.join silently steps over null (match std.jsonnet version)

.gitignore, linter/README.md, linter/find_variables.go, linter/jsonnet-lint/cmd.go, linter/linter.go, parser/context.go, parser/parser.go
No tests yet. It has currently one feature - reporting unused variables. Internally it keeps all the usages. Expect rough edges. I have only run it on a few files by hand so far.
=> Very basic, experimental linter

ast/ast.go, desugarer.go, parser/context.go, parser/parser.go, parser/parser_test.go, testdata/div4.golden, testdata/error_function_fail.golden, testdata/percent_bad2.golden, testdata/percent_format_str4.golden, testdata/string_plus_function.golden
We need this so we can output code in the manner it was written.
=> Introduce a Parens AST

interpreter.go
=> Do not assume that import path is always a filesystem path

ast/clone.go, desugarer.go
@sbarzowski @marcelocantos @benley
=> Clone ASTs to avoid aliasing and double-unescaping

jsonnet/cmd.go
Fixes #213
Consolidates the logic for handling the various --{ext,tla}-* parameters into two closures.
=> Refactor handling of --{ext,tla}-* flags

desugarer.go
=> Add missing error handling branch

cmd/jsonnet/cmd.go, testdata/assert_equal4.golden, testdata/assert_equal5.golden, testdata/assert_equal6.golden, testdata/percent_bad2.golden, testdata/percent_format_str4.golden, testdata/percent_format_str5.golden, testdata/percent_format_str6.golden, testdata/percent_format_str7.golden
The diff looks much bigger than the actual change, I only de-dented a branch
=> Bring up-to-date with cpp version

testdata/import_various_literals_escaped.golden, testdata/importstr_various_literals_escaped.golden
@sbarzowski Any idea why CI didn't pick this up?
=> golden files were out of date

testdata/import_various_literals_escaped.golden, testdata/importstr_various_literals_escaped.golden
=> Change golden files back again;

travisBuild.sh
@sbarzowski I tried to run travisBuild.sh locally and ran into this.  Not sure this is the correct fix though.
=> Don't assume Go is in a specific directory

builtins.go, error_formatter.go, imports.go, interpreter.go, runtime_error.go, thunks.go, value.go
Many things were exported for no particular reason.
=> Unexport a bunch of symbols

internal/parser/context.go
Namely:
1) function body and optional params
2) object locals
=> Add missing cases in specialChildren

.travis.yml, travisBazel.sh
=> Check Bazel in Travis

c-bindings-tests/compat_test.py, c-bindings/c-bindings.go, c-bindings/internal.h, c-bindings/libjsonnet.cpp
=> Implemented jsonnet_import_callback c-binding

.gitignore, c-bindings/BUILD.bazel, python/_jsonnet.c, python/_jsonnet_test.py, python/test.jsonnet, setup.py, tests.sh, vm.go
It resolves #333
I have some implementation questions:
* What is the best way to get the [version](https://github.com/google/go-jsonnet/pull/336/commits/437829ff723978ca6a9060ca7579e37f54a741d6#diff-2eeaed663bd0d25b7e608891384b7298R26)
* Should we copy entire `python` folder?
=> Use backed by go-jsonnet for python extension

.travis.yml, tests.sh, travisBuild.sh
=> Compile package in 32-bit mode

builtins.go, testdata/builtinManifestJsonEx.golden, testdata/builtinManifestJsonEx.jsonnet
minimal repo: https://play.golang.org/p/GQBNMe6k_nm
https://stackoverflow.com/questions/28595664/how-to-stop-json-marshal-from-escaping-and\nminimal 
fix proof: https://play.golang.org/p/SJM3KLkYW-
resolves #423
=> fix(stdlib): 🐛  manifestJsonEx was escaping HTML

builtins.go
=> Fix std.manifestJsonEx parameter names

c-bindings/c-bindings.go, c-bindings/handles.go, c-bindings/internal.h, c-bindings/libjsonnet.cpp
=> issue-433 increase the number of constructed Jsonnet handles.

BUILD.bazel, README.md, cmd/jsonnet-deps/BUILD.bazel, cmd/jsonnet-deps/cmd.go, cmd/jsonnet/cmd.go, vm.go
Fixes https://github.com/google/jsonnet/issues/833.
=> jsonnet-deps: Jsonnet static dependency parser

c-bindings-tests/compat_test.py, c-bindings-tests/jsonnet_import_test/multi.jsonnet, c-bindings-tests/jsonnet_import_test/stream.jsonnet, c-bindings/c-bindings.go, c-bindings/libjsonnet.cpp
With this change we cover 100% of the C API.
=> Add support for missing functions in C-bindings.

python/_jsonnet.c
We apply the same changes as:
https://github.com/google/jsonnet/pull/814
=> Release GIL in Python bindings.

internal/program/desugarer.go, testdata/assert3.golden, testdata/assert_failed.golden, testdata/assert_failed_custom.golden
=> Fix missing stack trace entry for assertions.

c-bindings-tests/compat_test.py, c-bindings/c-bindings.go
I've added `formatOptions` field to `vm` struct to keep API compatibility with the C++ version.
=> Add format APIs to C bindings

cmd/jsonnet/cmd.go
=> Prevent keeping files open for too long.

builtins.go
=> Add std. manifestJsonMinified

internal/program/static_analyzer_test.go
It should not make the difference.
=> Stop depending on nil vs empty slice in a test.

internal/parser/string_util.go
Equivalent change to https://github.com/google/jsonnet/pull/898
=> Equivalent change to https://github.com/google/jsonnet/pull/898

builtin-benchmarks/manifestTomlEx.jsonnet, builtins.go, builtins_benchmark_test.go, testdata/builtin_manifestTomlEx.golden, testdata/builtin_manifestTomlEx.jsonnet, testdata/builtin_manifestTomlEx_array.golden, testdata/builtin_manifestTomlEx_array.jsonnet, testdata/builtin_manifestTomlEx_null.golden, testdata/builtin_manifestTomlEx_null.jsonnet
Go implementation of `manifestTomlEx` - this was taking more than half the time in a large jsonnet repo. This implementation is ~15X faster
```
benchmark                                  old ns/op      new ns/op      delta
Benchmark_Builtin_manifestTomlEx-12        120747591      7949586        -93.42%
```
Helps with of https://github.com/google/go-jsonnet/issues/111
=> feat: implementation of manifestTomlEx in Go (15 X faster)

linter/internal/types/stdlib.go, testdata/stdlib_smoke_test.golden, testdata/stdlib_smoke_test.jsonnet
Add linter metadata for std.get function
Fixes #626
=> feat: add support linter std get

bazel/deps.bzl
=> Revert "Don't pass version to `go_register_toolchains()` by default"

go.mod, go.sum
=> Bump go to 1.17

builtins.go, testdata/builtin_member_string.golden, testdata/builtin_member_string.jsonnet
This PR fixes https://github.com/google/go-jsonnet/issues/656 and adds a test case.
=> Fix std.member matching sub strings

debugger.go
This PR fixes compilation error caused by the conflict of `valueToString`.
The function in debugger.go was added in #739, but also added in builtins.go in #742.
=> chore: fix compilation error of valueToString in debugger.go

go.mod, go.sum
Also updates indirect dep golang.org/x/sys to v0.30.0.
=> Update golang.org/x/crypto to v0.33.0
