interpreter.go
main.go
main_test.go

Also:
* Made all types used in errors public.
* Made interpreter receiver a pointer.  This will reduce GC load for deep stacks.

Fix up lint errors.

---

desugarer.go

In Go `for i, val := range arr` creates a *copy*
so it was changing some temporary value.

Fix local bind body not being desugared

---

ast.go
desugarer.go
parser.go
parser_test.go
tests.sh

New features in parser and desugarer:
* Support for slices
* Support for methods
* Support for function sugar in locals
* Prevent crashes with obj/arr comprehensions
After this change evaluating stdlib doesn't crash.

Make it possible to evaluate stdlib

---

main.go

Given the following scenario
vm := jsonnet.MakeVM()
vm.ExtVar("foo", "bar")
calling the `ExtVar` and `ExtCode` methods of a vm result in a panic
because the map has not been initialized, this patch adds
initializes the map.
Signed-off-by: Sevki <s@sevki.org>

initialize the extMap

---

builtins.go

operator% is implemented in std.jsonnet and we already enable desugaring in https://github.com/google/go-jsonnet/pull/64. So those code can be safely removed.

eliminate unused code:

---

doc.go

```
No types marked with +gen were found. See http://clipperhouse.github.io/gen to get started, or type /tmp/go-build675261218/command-line-arguments/_obj/exe/main help.
exit status 1
doc.go:29: running "gen": exit status 1
```

Remove go:generate causing errors

---

builtins.go
interpreter.go

This is necessary for example for native functions
(which take json as arguments).
Standard "encoding/json" representation is used, but I have
mixed feeling about it. Not sure if treating json values as interface{}
is the right trade-off in our case.

Separate manifestation from serialization to string

---

builtins.go
evaluator.go
interpreter.go
value.go

Faster comparisons and IMO cleaner feeling overall.
It doesn't affect behaviour in any way.

Represent types as Go objects, not strings (give them pointer identity)

---

builtins.go
testdata/builtinObjectFieldsEx_bad.golden
testdata/builtinObjectFieldsEx_bad2.golden

Actually there was one (objectFieldEx) that was inconsistent, i.e.
it was available by a different name from what appeared in the stack
trace. This is now fixed.

Eliminate duplication in builtin names

---

interpreter.go
main_test.go
thunks.go
vm.go

NOTE: I have not yet tested this patch, as I cannot seem to run the `tests.sh` file. I am putting it up anyway just to make sure that I'm on at least the right track.
Currently, `jsonnet.VM#NativeFunction` takes a single argument of type
`jsonnet.nativeFunction`. This is ok for internal use, but because this
type is private to the `jsonnet` package, it is not possible for a
third party to call this function (since it can't instantiate the type).
This commit makes this type public to remedy this problem.

Rename `jsonnet.nativeFunction` -> `jsonnet.NativeFunction`

---

builtins.go
cmd/dumpstdlibast.go
dump/README.md
dump/dump.go
dump/dump_test.go
dump/pointermap.go
dump/utils.go
interpreter.go
vm.go

utter(github.com/kortschak/utter) is powerful to dump go data structure as go source code.
To dump ast and make the source code usable in other package, we need make "loc" and "freeVariables" in NodeBase struct as public. Otherwise, the dumped source code can only be used in "ast" package.
This pr is just send out for further comment and feedback and demonstrates that pre-parse stdlib is practicable. If this way looks good, I will close this and send several elaborate PRs:
* make "loc" and "freeVariables" in NodeBase struct as public
* add a "Dump()"  function in "ast" package, which leveraging utter(github.com/kortschak/utter)
* add a dump command line tool which can read a jsonnet file and dump it's ast. The dump tool will call the "Dump()"  function in "ast" package
* using the dump …

experiment dump ast to source code

---

ast/util.go
static_analyzer.go

Sort FreeVariables slice. Otherwise, every time we regenerate the standard library AST will produce different output, even if "std.jsonnet" keeps unchange.

Sort FreeVariables slice

---

imports.go

MemoryImporter is convenient to use in an embedded VM setting when an import needs to be passed to a script.
Signed-off-by: Kuat Yessenov <kuat@google.com>

Expose MemoryImporter data

---

jsonnet/cmd.go

The long option --output-file was not working, due to what looks like a
cut and paste error, leaving --exec as the string to test for.

jsonnet: Fix --output-file command line option

---

_gen.go
error_formatter.go
jsonnet/cmd.go
main_test.go
vm.go

The imports in "_gen.go" were not used, compiled, or
apparently useful so remove.
The color field in the ErrorFormatter was never set
to true and never used. This brought in many unused
dependencies including x/sys/unix that aren't ever
used.
While these aren't huge issues, they add significant
un-needed burden when reviewing imports. I have to
remove them before using the package.
Fixes google/go-jsonnet#131

Remove unsued dependencies

---

error_formatter.go
value.go
vm.go

EvaluateSnippetMulti comment was copied from another function by mistake.
Add a space between the license and the package name.
Add a few periods after the comments.
Fixes google/go-jsonnet#160

jsonnet: fix docs, correct EvaluateSnippetMulti

---

jsonnet_test.go
main_test.go

I would like to be able to run go testsuite on C++ codebase. To do so I need to decouple the tests from the current implementation. This change is the first step.

Basic refactoring - towards shared e2e tests

---

main_test.go
testdata/native_error.golden
testdata/native_error.jsonnet

A native function returning an error should be reported as a runtime
error, with a stack trace.

Add test case for native function returning error

---

.travis.yml
README.md
builtins.go

It seems like it was broken on older compilers
since pregenerated stdlib AST.
Add go 1.8.x to travis, so that we have a chance
of catching when our "known to work" no longer holds.

Oldest version known to work = Go 1.8, closes #177

---

imports.go

There was a trivial bug, which disabled caching
of parsed, desugared and analyzed code. So imports
were only cached on data level, not on executable
ast level.
This change will likely result in ~10x speedup
for some users.

Fix processing the same file many times

---

jsonnet/cmd.go

Instead of reading the files directly for --tla/ext-*-file, just add a
code snippet that does an import or importstr.
This makes relative imports work when the code-file path is not in the
current directory. It also makes the import lazy so if the arg/var is
not referenced, the file does not have to exist.
Fixes: google/jsonnet#452

Convert --tla/ext-*-file to imports

---

.gitmodules
.travis.yml
README.md
tests.sh

Also:
- Run `tests.sh` in travis-ci.
- `tests.sh` updates the submodule and run its tests against go-jsonnet.
- `tests.sh` also runs `go test ./...` (but not in travis-ci, which does so via goverage).
- Update `README.md` to explain how to run tests.
Currently, the submodule points to the latest Jsonnet release, v0.9.5.

Add C++-Jsonnet submodule for tests

---

dump/dump.go
dump/dump_test.go

Change the dump code so that it hides the values of variable
definitions if they're large. This means that godoc.org should
be able to deal with the output, and the godoc output is
readable without needing to read through a huge struct literal definition.
Other approaches might be to always generate an extra variable
(seems unnecessary) or to pass to writer explicitly to the dump
methods rather than swapping s.w out temporarily. The former
seems unnecessarily intrusive to the usual output; the latter
seemed unnecessarily intrusive to the source itself.
YMMV.

godoc.org-compatible ast package

---

imports.go
interpreter.go
jsonnet_test.go
parser/parser_test.go
testdata/import_twice.golden
testdata/import_twice.jsonnet

As discussed in https://github.com/google/go-jsonnet/issues/190

Better Importer interface

---

parser/context.go

ref: https://github.com/google/go-jsonnet/issues/226

[BUG] Support *ast.ObjectComp and *ast.Parens in Node.Children()

---

ast/fodder.go
parser/lexer.go
parser/lexer_test.go

I also rewrote lexer_test to use individual tests for each case instead of iterating through an array.  While not as dense on the page, the density of information is about the same and this way you can get more useful stacktraces as well as easily select specific tests to run.

Lex fodder in a manner compatible with C++

---

parser/context.go

this allows traversing the Binds in a Local via the parser.Children() call on a Local Node.

pull Local.Binds[].Body out via specialChildren

---

travisBuild.sh

This commit refactors travisBuild.sh to support building pushed branched on top
of PRs and tags.
This was prompted by enabling travis on a forked repository. The development
flow then becomes:
- Fork google/go-jsonnet
- Enable travis on forked repository
- Push branch to forked repository
- Travis runs on the pushed branch
- Submit pull request once happy and tests pass in the forked repository
I tested 3 scenarii and they seem behave nicely:
- Running CI for pushed branch
- Running CI for tag
- Running CI for a Pull Request
As a side note, the previous error path didn't work as intented:
- The TRAVIS_PULL variable didn't exist
- We weren't exiting with a non 0 value in the else branch, so the build
succeeded instead of failing when travisBuild.sh didn't know what to do
with the pushed …

travis: Support building pushed branches

---

jsonnet/cmd.go
std/std.jsonnet
testdata/assert_equal4.golden
testdata/assert_equal5.golden
testdata/assert_equal6.golden
testdata/percent_bad.golden
testdata/percent_bad2.golden
testdata/percent_bad3.golden
testdata/percent_format_str4.golden
testdata/percent_format_str5.golden
testdata/percent_format_str6.golden
testdata/percent_format_str7.golden
testdata/percent_mod_int5.golden

This is an implementation of https://github.com/google/jsonnet/issues/195 for the Go version since the concerns mentioned in that issue are of no concern in a Go application. It's just a very quick fix done for my own needs, feel free to reject in case you don't want any divergence from the C++ implementation.

Automatically create output folders

---

vm.go

Right now, SnippetToAST provides a `Node` but nothing consumes it it seems.
This is mostly to open the discussion. My goal is to use jsonnet as a reformatter in streaming objects.. Performance is going to be paramount for us, reusing the AST is a start.
Nice work in here by the way.. love the project :)

Expose Evaluate functions, to be able to reuse the AST from `SnippetToAST`

---

go.mod
go.sum

Updating projects using libraries that were recently updated to support Risc-V.
Go upstream work is tracked on: https://github.com/golang/go/issues/27532
Risc-V software support tracker on https://github.com/carlosedp/riscv-bringup

Update x/sys to a newer version that supports Risc-V architecture

---

WORKSPACE
astgen/BUILD.bazel
c-bindings/BUILD.bazel

Treating the "cpp-jsonnet" Git submodule as a separate local Bazel repository precludes use of the "go-jsonnet" repository from other workspaces, as Bazel misinterprets the relative path to the local
"cpp-jsonnet" repository. Instead, use the Git submodule content directly along the package path from the workspace root.
Thanks to @werkt for pointing out the root of the problem.

Eliminate Bazel local repository for "cpp-jsonnet" submodule

---

README.md
WORKSPACE
bazel/deps.bzl
bazel/repositories.bzl

In order to rely on the _go-jsonnet_ Bazel repository as an external dependency from other Bazel projects, until [it becomes possible to load a _WORKSPACE_ file](https://github.com/bazelbuild/bazel/issues/1943), it's necessary to first declare the repositories on which this repository depends (_rules_go_ and _gazelle_), and then to load file from those two repositories and call macros to initialize them.
Expose two files to handle these steps:
- _bazel/repositories.bzl_ . 
Defines the `jsonnet_go_repositories` macro.
- _bazel/deps.bzl_ . 
Defines the `jsonnet_go_dependencies` macro.
Use these files and the macros they define within this repository's _WORKSPACE_ file, as a dependent repository would do in its _WORKSPACE_ file.

Allow use of "go-jsonnet" Bazel repository as an external dependency

---

builtins.go
interpreter.go
value.go

So far I did this in a way which is intended to be minimally
invasive, even at the cost of worse performance and some weirdness.
Most importantly valueCachedObject should probably replace valueObject
interface to avoid some indirection (and it shouldn't be at the same
"level" as valueSimpleObject/valueExtendedObject (these should no longer
even be values on their own).
This is a reasonable proof of concept, which we can try benchmarking
on the real world code.

Object field caching

---

ast/stdast.go
c-bindings/c-bindings.go
cmd/dumpstdlibast/dumpstdlibast.go
cmd/jsonnet/cmd.go
interpreter.go
jsonnet_test.go

The initially empty ast.StdAst was created to break the circular
dependency. The generation of stdlib AST used to depend on
the primary "jsonnet" package, which meant that "jsonnet"
could not depend on it directly. Hence stdlib needed to be put
in the ast package. Now dumpstdlibast no longer depends on Jsonnet,
so we can get rid of this complication.
All code using ast.StdAst should now use astgen.StdAst.

Eliminate the unnecessary ast.StdAst

---

imports.go
interpreter.go
vm.go

* It adds new API which allows using VM for importing
files in external tools "just as Jsonnet would". This is
primarily intended for use in static analysis tools.
* Imports are now cached between evaluate calls. This may improve
performance significantly for some users. I would like to add
some way of achieving this with commandline in the future.
* Additional layer of caching was internally added - AST level.
This was necessary so that Jsonnet could always return the same
exact AST when asked multiple times (meaning the same pointers).

Better importing (caching & public API)

---

parser/context.go
toolutils/BUILD.bazel
toolutils/ast.go

As `parser` was moved to `internal/parser`, it is not possible to import it into
external projects anymore.
However, `parser.Children()` is handy to use in static analysis tools, so it is
worth exporting. This does that by adding a stub package
`github.com/google/go-jsonnet/parser` that wraps the internal function.
Signed-off-by: sh0rez <me@shorez.de>
Closes #326

feat(parser): export parser.Children

---

.travis.yml
README.md

Go 1.8 has been unsupported for more than a year.

Bump officially supported Go version to 1.11

---

builtins.go
imports.go
interpreter.go
value.go

When adding long strings, don't copy them immediately. Instead
build long strings only when their contents are requested.
This allows to build a long string from parts, using a regular
operator+ in linear time. This lets users to worry much less
about using std.join etc.
If indexing the string is mixed with building it using operator+
the behavior can still be quadratic. We may want to address it in
a later change.
Depends on: #229

Smart strings

---

README.md

It seems the build instructions were outdated and/or incorrect.
These are the changes I had to make in order to build the project.

Fix build instructions and git clone

---

builtins.go

builtins.go: Prevent int overflow in bounds checks for bitwise operators

---

.travis.yml
setup.py
tests.sh

This resolves #369 
I decided to use `pytest` as a testing framework. It has some restrictions with python versions and I am not sure it is a good choice. Please let me know if my concerns are fair.
p.s. I manually disabled `setup.py test` command.

Replace `setup.py test` with pytest command

---

c-bindings/c-bindings.go

Removing a rather noisy debug message in c-bindings which I believe was added for that purpose only and should have been deleted.

Remove bindings debug msg

---

cmd/jsonnetfmt/BUILD.bazel
formatter/BUILD.bazel
formatter/formatter.go
internal/formatter/BUILD.bazel

Exposes what I consider a good public API from the `internal/formatter`
package.
Having a go-native formatter is an awesome thing, especially because it
allows shipping the formatter as part of other projects. It's also fair
to keep the formatter's code in `internal`, yet third party projects
should have a way to use relevant parts of it.
**Note:** Ran `bazel run //:gazelle`, it modified other formatter related `BUILD.bazel` files as well ... is this expected?

feat(api): expose formatter

---

internal/dump/dump_test.go

TestSdumpLargeDefinition is depnding on a global state change made by TestSdumpReusedPointers. It can't pass if it runs before TestSdumpReusedPointers.
Fixes internal auto-filled bug.

fix order-dependent test

---

MANIFEST.in

Here's a quick fix for #371 .  I've done the bare minimum required to create a sdist (or wheel if you have a way to build them) that can be pip installed.  To test:
```
python3 setup.py sdist
pip install dist/gojsonnet-0.15.0.tar.gz
```
You should then be able to `import _gojsonnet` in the Python REPL.
Fair warning, I have no idea why or how the c-bindings are finding `libjsonnet.h`, I mostly just followed the error messages and included the missing files until it worked.  If there's a better way to include that I'm happy to make changes.

Add necessary files to MANIFEST.in

---

internal/parser/parser.go

CommaFodder was not cleared between arguments,
so when there was no commaFodder and the argument
was named a previous one was duplicated.
Fixes #411.

Fix duplicated fodder (#411).

---

Makefile
README.md
builtin-benchmarks/manifestJsonEx.jsonnet
builtins.go
builtins_benchmark_test.go

```
❯ make benchmark FILTER=Builtin_manifestJsonEx
go build ./cmd/jsonnet
./benchmark.sh Builtin_manifestJsonEx
Running Before Test... (10s)
Running After Test... (10s)
benchmark                               old ns/op     new ns/op     delta
Benchmark_Builtin_manifestJsonEx-16     22656394      7502016       -66.89%
```
---
EDIT
~I could use a small amount of help here. The test is currently failing seemingly because the output doesn't match. I suspect it's some sort of whitespace issue, but I can't tell.~
Fixed the problem, I was setting an initial indentation.

perf(stdlib): ⚡️  implement manifestJsonEx as native Go

---

.github/workflows/release.yml
.goreleaser.yml

This add a github action to build binaries and add them as release artefacts using goreleaser (https://goreleaser.com/).
It seems to work fine - see e.g. https://github.com/PaulRudin/go-jsonnet/releases/tag/v0.0.200. I've checked that the binaries for linux amd64 work.

Add github action to build binaries with goreleaser.

---

ast/location.go
c-bindings/c-bindings.go
cmd/dumpstdlibast/BUILD.bazel
cmd/dumpstdlibast/dumpstdlibast.go
cmd/jsonnet/cmd.go
imports.go
internal/formatter/jsonnetfmt.go
internal/parser/lexer.go
internal/parser/lexer_test.go
internal/parser/parser.go
internal/parser/parser_test.go
internal/program/program.go
jsonnet_test.go
main_test.go
vm.go

We used to treat dummy paths like `<stdin>`, `<std>`, `<extvar>` as
real import locations, which causes obvious problem for importers.
After this change we consistently pass "" (an empty string) as location
for non-imported paths.
We exposed new functions to properly handle all paths.
The first function family, EvaluateFile*  allows evaluating
a Jsonnet program at a specified importable path. It should
be used in most cases.
The second function family, EvaluateAnonymousSnippet* allows evaluating
a snippet without an importable path. It should be used for situations
like the code passed as a commandline argument, stdin, etc.
The old function family, EvaluateSnippet* is now deprecated, but
works the same as before, i.e. the passed filenames are treated
as imported paths.
Changes are …

Anonymous Import Locations

---

.goreleaser.yml

This makes the goreleaser output two debian packages. One for jsonnet,
and another for jsonnetfmt. Since we don't use cgo, we don't need to
take dependencies, as we're fully statically linked. The package
name for this package will be go-jsonnet, and go-jsonnetfmt. There
is a package that Ubuntu has released that's based on the C++
version. We have a conflict statement with it in order to
avoid people installing both.
We can ask the C++ package to rename itself to jsonnet-c++, and then
add a provides for the package name jsonnet. The reason to not name
this jsonnet immediately, even though the Go version if meant to
supercede the C++ version, is that this doesn't fully implement the
C++ version (for example, man pages).

Add debian package build to goreleaser

---

astgen/BUILD.bazel
bazel/repositories.bzl
c-bindings/BUILD.bazel

This PR add cpp_jsonnet as an `http_archive` rule and refer it as an external repo in Bazel rules. This is the more natural way of referring other repositories on Bazel, and is an alternative way to fix #375. Comparing to the `git_repository` approach, this allows other repositories to use go-jsonnet as a `go_repository` and use `gazelle update-repos` to import it from the `go.mod` file, which fixes #392.
TODO: either set up a CI check to make sure the submodule has the same version as the one downloaded by `http_archive`, or remove the git submodule if nothing else is using it.

Using cpp_jsonnet as external repo

---

c-bindings/handles.go

Since all VM instances are managed by a global map, read/write of the
global map must be protected by a mutex.

Support creating VMs from multiple threads in C-bindings

---

.goreleaser.yml

I was not able to find any evidences of darwin builds being disabled intentionally. Considering
the [documentation](https://goreleaser.com/customization/build/) I suspect that this was by
mistake. Currently, each list item is applied individually (OR). If I'm wrong, please discard this
PR and share your reasoning.

Fix builds filter ro re-enable darwin builds

---

jsonnet_test.go
vm.go

Currently ext and TLA vars can be set but not reset. This makes
re-using VMs that have different variables impossible.
Add VM methods to be able to reset ext and TLA vars

Allow reset of ext and TLA vars for VM reuse

---

imports.go
interpreter.go
jsonnet_test.go
vm.go

Allow configuration of a VM with an external code variable that has been pre-parsed into an AST node.
This allows a caller to pre-parse a large object into a node and re-use that for multiple VMs. The cost
of converting the object to an ast.Node is incurred only once by the caller as opposed to having this
eagerly incurred (whether or not the object is used) before the eval.

allow initialization of external and TLA code variables from an AST node

---

.pre-commit-hooks.yaml

Once this is merged, we can update https://pre-commit.com/hooks page for users to use this hook.

pre-commit hook to format jsonnet files

---

builtins.go
interpreter.go
jsonnet_test.go
vm.go

Allow setting a different output stream than `os.Stderr` for `std.trace`.
This is requested by #394.

Allow setting a different output stream than os.Stderr for std.trace

---

builtins.go
testdata/builtinManifestJsonEx.golden
testdata/builtinManifestJsonEx.jsonnet

This PR fixes a regression in std.manifestJsonEx that caused the
standard library function to error when the given value was an array.
It also adds a test case to prevent regressions in
std.manifestJsonEx accepting arrays as values.
fixes: #515 
Implements fix suggested by @sbarzowski in https://github.com/google/go-jsonnet/issues/515#issuecomment-779123853

Fix manifest json ex regression

---

c-bindings-tests/compat_test.py
c-bindings/c-bindings.go
c-bindings/internal.h
c-bindings/libjsonnet.cpp

Support different output streams than os.Stderr for std.trace (C API)

---

ast/identifier_set.go
ast/util.go
ast/util_test.go

Hello. While profiling another tool ([Grafana's Tanka](https://github.com/grafana/tanka)) I've found that 13% of memory profiling was spent at `ast.IdentifierSet.ToOrderedSlice`. After checking the code I've found a small change that drastically improves not only memory consumption in a stable way (only 2 allocations per call to `ToOrderSlice`, regardless the size of the output slice) but drastically improves the performance of this and `ToSlice` methods.
I've added some benchmarks to test this and found the following: with the code at [current master](https://github.com/google/go-jsonnet/blob/63a452246db4e1eda7d55daea445f83c7bbf1b5d/ast/util.go#L31-L38) I get these numbers:
```
goos: darwin
goarch: amd64
pkg: github.com/google/go-jsonnet/ast
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz …
```

IdentifierSet performance improvements

---

cmd/jsonnetfmt/cmd.go
internal/formatter/add_plus_object.go
internal/formatter/fix_plus_object.go
internal/formatter/jsonnetfmt.go
internal/formatter/remove_plus_object.go

Implements: https://github.com/google/go-jsonnet/issues/496
- I reused the `fix_plus_sign.go` file instead of removing it and creating a new one. Let me know if you would like rename it.
- I don't add new `Fodder` nor interact with existing `Fodder` in any way. I think that is correct but that's for someone more knowledgeable to say.
- I'm not sure if the comments are correct so please check them.

Make jsonnetfmt add plus objects instead of removing them

---

.pre-commit-hooks.yaml
README.md

updates / extends #512:
- documented usage in `README.md`
- added `jsonnet-lint` to available hooks
- set `minimum_pre_commit_version` to `2.10.1`, see [this](https://github.com/pre-commit/pre-commit/pull/1789) PR which was [added](https://github.com/pre-commit/pre-commit/releases/tag/v2.10.1) in `v2.10.1`
- removed `additional_dependencies` as pre-commit automatically installs the cloned repository. (the way the hook was configured before caused a duplicate clone and installation).

updated pre-commit config and readme

---

linter/internal/types/stdlib.go

This commit corrects return type of the `member` function from the
standard library.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

linter: correct the return type for member

---

cmd/jsonnet-lint/cmd.go
linter/linter.go
linter/linter_test.go

Modify jsonnet-lint to accept multiple input files

---

.goreleaser.yml

This PR aims to add packages for `macOS` at releases.
For now, binary packages for macOS are missing at the release page even though `goreleaser` settings include macOS at `goos`.
This is because ignore config of `goreleaser` are incorrect.
In the current config, all of the macOS(`darwin`) will be ignored.

Fix gorelaser configs to properly build darwin packages

---

README.md

Since go `1.17` the installation of binaries with `go get` is deprecated. The README.md was updated to reflect this.
I also highlighted the fact that the version suffix is mandatory. This information can be found by running `go help install`, but I believe explicitly specifying it may reduce the entry barrier.

Document installation for go >= 1.17

---

internal/formatter/jsonnetfmt.go
internal/formatter/unparser.go

See https://github.com/google/go-jsonnet/pull/576
These changes were supposed to be included but I forgot to push with `-f`

The rest of "Corresponding change to formatter"

---

.github/workflows/release.yml

I don't mean to overstep, so please, feel free to drop this one. But maybe this PR has an encouraging effect.
My motivation for this PR is to make the darwin_arm64 artifact available as part of the release. At this point, [Goreleaser](https://github.com/goreleaser/goreleaser/issues/1952) automatically supports it, if the go version, used to build the artifact, is >= 1.16
The *Installation instructions* already refers to Go v1.17 and above, and the `README.md` clearly states:  *We recommend always using the newest stable release of Go.* ;)

Bump Go build version to 1.17

---

bazel/deps.bzl

Adds a `go_sdk_version` to register a specific Go toolchain.
Motivation for the change is here: https://github.com/bazelbuild/rules_jsonnet/pull/153

Add go_sdk_version parameter

---

linter/internal/types/stdlib.go
testdata/stdlib_smoke_test.golden
testdata/stdlib_smoke_test.jsonnet

feat: Add missing linter metadata for std.manifestTomlEx function

---

builtins.go

As mentioned in #570.
The approach here is similar to the [cpp implementation](https://github.com/google/jsonnet/blob/master/core/vm.cpp#L1494) of `jsonnet`, we catch the problem early and inform the user with a sensible message, as opposed to a large panic stacktrace being shown.

fix: no panic with negative index to std.substr

---

.goreleaser.yml

Fix #542.
This PR adding maintainer info to a deb package of `jsonnetfmt`.

Add maintainer info to a deb package of jsonnetfmt

---

bazel/deps.bzl
go.mod
go.sum

We are experiencing issue with checksum mismatch. Attempting to bump dependency to fatih/color to fix this.
````
$ go install github.com/google/go-jsonnet/cmd/jsonnet@latest
go: downloading github.com/google/go-jsonnet v0.18.0
go: downloading github.com/fatih/color v1.10.0
go: downloading sigs.k8s.io/yaml v1.1.0
pkg/mod/github.com/google/go-jsonnet@v0.18.0/cmd/jsonnet/cmd.go:28:2: github.com/fatih/color@v1.10.0: verifying module: checksum mismatch
downloaded: h1:Tr0pkf8RgNWBadn2nj0GE5+l8S9ABNy19/ElCYCpzGg=
sum.golang.org: h1:s36xzo75JdqLaaWoiEHk767eHiwo0598uUxyfiPkDsg=
SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see …
```

Bump dependency to fatih/color

---

main_test.go
testdata/native_panic.golden
testdata/native_panic.jsonnet
thunks.go

Previously, you'd get an "INTERNAL ERROR: (CRASH)" with a full backtrace
and a link to file a bug against go-jsonnet.

feat: Report native function panics as runtime errors.

---

linter/internal/types/stdlib.go
testdata/stdlib_smoke_test.golden
testdata/stdlib_smoke_test.jsonnet

Adds support for the `std.manifestJsonMinified` to the linter
Helps #610

feat: add support to the jsonnet linter for std.manifestJsonMinified

---

go.mod
go.sum

closes https://github.com/google/go-jsonnet/issues/611
Generated with `go get -u golang.org/x/sys` and `go mod tidy`

Bump golang.org/x/sys

---

ast/identifier_set.go
builtins.go
interpreter.go
thunks.go
value.go

Hey folks, just a small patch to add size hints to maps where it seemed appropriate. I'm not sure if I'm missing an obvious reason these were left out initially. But given `go-jsonnets` use of maps this could be a low hanging fruit for cutting down on allocations.

perf: add size hint to map creation

---

go.mod
go.sum

Relates to: https://github.com/google/go-jsonnet/pull/623/files
Generated with: `go get -u golang.org/x/sys`
```
go install github.com/google/go-jsonnet/cmd/jsonnet@latest
../../../.asdf/installs/golang/1.19.1/packages/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
../../../.asdf/installs/golang/1.19.1/packages/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../.asdf/installs/golang/1.19.1/packages/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable …
```

Bump golang.org/x/sys again

---

.golangci.yml
ast/ast.go
ast/fodder.go
ast/location.go
builtins.go
c-bindings/handles.go
cmd/jsonnet/cmd.go
cmd/jsonnetfmt/cmd.go
error_formatter.go
imports.go
internal/dump/dump.go
internal/errors/static_error.go
internal/formatter/sort_imports.go
internal/parser/context.go
internal/parser/lexer.go
interpreter.go
runtime_error.go
thunks.go
value.go
vm.go

There is a small amount of heap allocations that can be shaved off by making sure that all of the structs are aligned correctly. I've rearranged structs to ensure they are padded correctly and added a lint rule to enforce this in the future.
There are few ignored structs as I don't think contribute to the runtime memory usage. They could also be fixed up at a later time.
I've also fixed a small amount of other lint issues.
References: 
- https://betterprogramming.pub/how-to-speed-up-your-struct-in-golang-76b846209587
- https://go101.org/article/memory-layout.html

memory align structs

---

c-bindings/c-bindings.go
c-bindings/internal.h
c-bindings/libjsonnet.cpp

This adds the realloc function as an export in c-bindings.go so that it is included in the generated header and can be used by dependent libraries. No implementation details changed, just the piping for exporting the function.
Tested manually by using the exported function in another binary.
Addresses #562

c-bindings: Add jsonnet_realloc export

---

bazel/deps.bzl

This should fix #619 where `jsonnet_go_dependencies()` fails because a go toolchain has already been registered.

Don't pass version to `go_register_toolchains()` by default

---

imports.go

FileImporter should use "path/filepath" not use "path".
package "path" will not work properly on non-*nix systems, such as windows

fix FileImporter not work on windows

---

bazel/repositories.bzl
update_cpp_jsonnet.sh

Unlike naive `go build`, bazel builds generate `astgen/stdast.go` on the fly from cpp_jsonnet's stdlib.  Cool.
Previously however, the cpp_jsonnet versions in git submodule (used by naive `go build`) and bazel `http_archive` declarations were not in sync.  Not so cool.
This meant `bazel test //:go_default_test` failed on `TestEval/testdata/stdlib_smoke_test`, since the stale bazel cpp_jsonnet version lacked `std.get`.
This PR updates cpp-jsonnet to match git submodule version and teaches `update_cpp_jsonnet.sh` to update the cpp_jsonnet reference in `bazel/repositories.bzl` too.

Update bazel cpp_jsonnet reference to match git submodule

---

bazel/deps.bzl
bazel/repositories.bzl
go.mod
go.sum

Update `golang.org/x/sys` package to address golang/go#51706
Update bazel `rules_go` to address bazelbuild/rules_go#3199

Fix bazel builds on recent macOS

---

linter/BUILD.bazel
linter/internal/common/BUILD.bazel
linter/internal/traversal/BUILD.bazel
linter/internal/types/BUILD.bazel

Update BUILD.bazel files so `bazel build //cmd/jsonnet-lint` works
again.

Fix jsonnet-lint bazel build

---

c-bindings/BUILD.bazel

Add missing bazel dependency so `bazel build //c-bindings` works again.

Fix //c-bindings bazel build

---

.github/workflows/ci.yml

If it's not tested, then it doesn't work.  Add a CI test that
executes `bazel build //...` and `bazel test //...`, in addition to
the non-bazel build system.

Add a CI test that exercises bazel builds

---

README.md

This would close https://github.com/google/go-jsonnet/issues/634 and avoid similar issues in the future.
It makes it clear than you can also install other tools, not only `jsonnet`, from the `cmd/` directory. I used `jsonnet-lint` as an example.

docs: add explicit mention for installing other tools in `cmd/`

---

.goreleaser.yml
cmd/jsonnet-lint/cmd.go

This PR should add jsonnet-lint to all the releases.
I haven't worked with a go releaser before. I think I figured out how the releases work for jsonnet and jsonnetfmt; I added similar stanzas for jsonnet-lint.

Adds jsonnet-lint to the releases

---

.goreleaser.yml

This should add `jsonnet-deps` to the release artifacts so that it is included in the release bundles in github:
https://github.com/google/go-jsonnet/releases
This is my first time using goreleaser so my apologies if I did something silly here.

adding jsonnet-deps to release

---

interpreter.go

Add support to return int based value from native functions golang implementations.
This is related to https://github.com/google/go-jsonnet/issues/671

feat: Int support for native functions impl

---

formatter/formatter.go
internal/formatter/jsonnetfmt.go

This is a rebased version of #530 by @tomwilkie:
> (Opening this for discussion, see https://github.com/google/go-jsonnet/issues/389)
> 
> I've build a little tool that does some modifications to jsonnet files (updating docker image versions in them), and wanted to use the pretty-printing code to write out the modified AST.
> 
> This is a minimal set of changes that allow me to do that.

Expose "unparse", FormatNode and RawAST

---

debugger.go
error_formatter.go
interpreter.go
runtime_error.go
vm.go

This PR adds an extension point for future debugger implementations.
We first investigated having the entire debugger codebase only use go-jsonnet as a dependency, but many of the fields and types needed to implement this are not exposed to external packages.
To solve this, we added a new `Debugger` type, which allows debugging frontends to control the evaluation of a specific file.
The API type is heavily inspired by the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) and can be used to implement basic debugging functionality like:
* Stepping through evaluation
* Setting Breakpoints
* Automatically breaking on exceptions
* Viewing a rudimentary stack trace
* Inspecting variables at runtime
Example implementations of clients using this interface can be found …

feat: add debugger support

---

interpreter.go

Close #752
This pull request is similar to #741 , but this pull request fixes a bug of #741 .

fix: fix conversion from int to float64

---

bazel/repositories.bzl

Pulling the `go-jsonnet` `v0.20.0` repository via Bazel and building locally results in an older version of `std.libsonnet` being bundled into the binary.  As a result, enhancements that were made as part of `v0.20.0` are not included.
It appears the `cpp_jsonnet` git submodule was bumped to the appropriate commit in https://github.com/google/jsonnet but the git hash and checksum from `bazel/repositories.bzl` was not.  
Update `bazel/repositories.bzl` to use the correct `v0.20.0` `cpp_jsonnet` dependency.

fix: bump cpp_jsonnet dependency to align with v0.20.0 release

---

MODULE.bazel
ast/BUILD.bazel
bazel/repositories.bzl
formatter/BUILD.bazel

This PR should fix the `bazel test` job on CI.

chore: update rules_go and gazelle version to fix bazel build

---

.github/workflows/ci.yml
.goreleaser.yml

See <https://github.com/goreleaser/goreleaser/blob/v2.0.0/www/docs/deprecations.md> for details.

chore: fix CI to follow the deprecation of goreleaser flags

---

linter/internal/types/stdlib.go
linter/testdata/stdlib_manifestYamlStream.jsonnet

Updates the linter for `std.manifestYamlStream` to include the optional parameters.

Add optional parameters to manifestYamlStream in linter

---

linter/internal/variables/find_variables.go
linter/testdata/local_used_in_assertion.jsonnet
testdata/local_in_object_assertion.linter.golden

This fixes #617.
While working on the fix an existing test was discovered that outlines the same bug. It could be fixed after fixing the bug itself.

Fix linter: using a local in an assertion.

---

debugger.go

The `valueToString` operation introduced by #742 is incompatible with the way the implementation from #739 as it tries to manifest an object from stack while the implementation needed by the debugger returns the value as-is without further evaluation.

fix: use debugValueToString for debugger operations

---

bazel/repositories.bzl
builtins.go
testdata/assert_equal4.golden
testdata/assert_equal5.golden
testdata/assert_equal6.golden
testdata/percent_bad.golden
testdata/percent_bad2.golden
testdata/percent_bad3.golden
testdata/percent_format_str4.golden
testdata/percent_format_str5.golden
testdata/percent_format_str6.golden
testdata/percent_format_str7.golden
testdata/percent_mod_int5.golden

This brings stdlib up to the latest (unreleased) version, which includes some new functions added in https://github.com/google/jsonnet/pull/1187
Also adds builtins for `atan2` and `hypot` to match the corresponding builtins in the C++ version.
The full stdlib changes can be seen from the changes to std.jsonnet at: https://github.com/google/jsonnet/compare/f45e01d632b29e4c0757ec7ba188ce759298e6d3...4487bfb8ba7ed7a3d91d79d4a1aa2205e7839558
(That shows all changes to the C++ repo from the previously embedded version to the newly embedded version)

Update stdlib and add builtins for atan2, hypot

---

.github/workflows/ci.yml
.github/workflows/publish-python.yml
.github/workflows/release.yml
.goreleaser.yml
pyproject.toml

- Pull in publish-python.yml from C++ jsonnet.
- Update to newer versions of various referenced GitHub Actions
- Minor changes to goreleaser configuration.
- Explicitly limit ci.yml to read-only permissions.
- Trigger release workflow manually, not on push-to-tag.

Update CI workflows

---

.github/workflows/publish-python.yml

Use the GitHub setup-go action to install Go, as it is not in the Mac OS runner images by default.
I tried but failed to get a Windows wheel build working, so that remains disabled for now.

CI: Build gojsonnet Python wheels on Mac OS

---

.bazelignore
.github/workflows/ci.yml
.gitignore
MODULE.bazel
examples/bazel/.bazelrc
examples/bazel/.gitignore
examples/bazel/BUILD.bazel
examples/bazel/MODULE.bazel
examples/bazel/example.jsonnet
examples/bazel/go.mod
examples/bazel/go.sum
examples/bazel/use_go_jsonnet.go

Attempting to update the Bazel registry for 0.21.0-rc2 (https://github.com/bazelbuild/bazel-central-registry/pull/4015) revealed a problem.
The rules_go go_sdk.download module extension function should not be given a name= attribute; that is only allowed in a root module, so it works for building just go-jsonnet but does not work when the jsonnet_go Bazel module is imported for use in another Bazel module.

Fixes for the Bazel module

---

c-bindings/BUILD.bazel
c-bindings/c-bindings.go
c-bindings/libjsonnet.cpp

This change allows us to build libgojsonnet from tarball downloaded from
GitHub releases.

Remove dependency on cpp-jsonnet submodule from C bindings

---

builtins.go

Problem: A recursive call within manifestYamlDoc() might fail but the return value is not checked.
Reproducible with:
```
$ jsonnet-2f73f61 -e "std.manifestYamlDoc({ x: { y: error 'foo' } }, quote_keys=false)"
"x:\n  "
```
Expected:
```
$ jsonnet-0.20.0 -e "std.manifestYamlDoc({ x: { y: error 'foo' } }, quote_keys=false)"
RUNTIME ERROR: foo
<cmdline>:1:31-42	object <anonymous>
...
```

fix: Unchecked error in std.manifestYamlDoc().
